### ISSUE TITLE
Can I use it in avatar?

### ISSUE THREAD

**Issue by SkyTNT** [SCRN-VRC/SimpNet-Deep-Learning-in-a-Shader#1]
I tried add it to my avatar.It works well in Unity, but not in VRChat.

In Unity:
![QQ截图20200904212747](https://user-images.githubusercontent.com/23373093/92244663-c3f17180-eef5-11ea-87cf-136ac3a4d065.png)

In VRChat:
![VRChat Screenshot 2020 09 04 - 20 58 13 62](https://user-images.githubusercontent.com/23373093/92244838-07e47680-eef6-11ea-95a0-e830fb2a6a61.png)

**Comment by SCRN-VRC** [comment]
Assuming you ripped out all the UI canvas, you'll have to do something with the cameras or VRChat will delete them.
![image](https://user-images.githubusercontent.com/49093147/92247915-7e837300-eefa-11ea-9750-c0a79d38eed6.png)
I circled the important things in red, put it on the UiMenu, turn off the Camera component, add a GUI layer, and use an animator to turn the Camera component back on again in game on load.

**Comment by SkyTNT** [comment]
It works!Thank you so much!
![QQ截图20200905005638](https://user-images.githubusercontent.com/23373093/92267096-e3e35e00-ef12-11ea-8187-7bbc685ffa53.png)
